#!/usr/bin/env bash
# 00_setup.sh — sanity-check the environment and create two isolated venvs.
# Idempotent: re-running is safe.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

log() { printf '[%s] %s\n' "$(date +%H:%M:%S)" "$*"; }

# ----------------------------------------------------------------------------
# 1. Hardware sanity check
# ----------------------------------------------------------------------------
log "== GPU =="
if ! command -v nvidia-smi >/dev/null; then
  echo "ERROR: nvidia-smi not found. citation-guard reproduce requires one GPU (≥ 80 GB)." >&2
  exit 1
fi
nvidia-smi --query-gpu=name,memory.total,memory.free --format=csv,noheader

FREE_MB=$(nvidia-smi --query-gpu=memory.free --format=csv,noheader,nounits | head -1)
if [ "${FREE_MB}" -lt 70000 ]; then
  echo "WARNING: less than 70 GB GPU free (saw ${FREE_MB} MiB). Generation may OOM." >&2
fi

# ----------------------------------------------------------------------------
# 2. uv (fast venv manager)
# ----------------------------------------------------------------------------
if ! command -v uv >/dev/null; then
  log "Installing uv (fast venv manager)…"
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="${HOME}/.cargo/bin:${PATH}"
fi
log "uv $(uv --version)"

# ----------------------------------------------------------------------------
# 3. Two isolated venvs under reproduce/.venvs/
# ----------------------------------------------------------------------------
mkdir -p .venvs
PQAVENV="${ROOT}/.venvs/pqavenv"
OSVENV="${ROOT}/.venvs/osvenv"

if [ ! -d "${PQAVENV}" ]; then
  log "Creating pqavenv (paper-qa)…"
  uv venv --python 3.12 "${PQAVENV}"
  VIRTUAL_ENV="${PQAVENV}" uv pip install -q paper-qa openai
fi

if [ ! -d "${OSVENV}" ]; then
  log "Creating osvenv (OpenScholar)…"
  uv venv --python 3.12 "${OSVENV}"
  VIRTUAL_ENV="${OSVENV}" uv pip install -q openai tqdm nltk spacy transformers requests pandas jsonlines bs4 numpy torch
  "${OSVENV}/bin/python" -c "import nltk; nltk.download('punkt_tab',quiet=True); nltk.download('punkt',quiet=True)"
fi

# vLLM venv: prefer system if available with vllm 0.21+, otherwise create one
if ! python3 -c "import vllm; assert vllm.__version__ >= '0.21'" 2>/dev/null; then
  VLLMVENV="${ROOT}/.venvs/vllmvenv"
  if [ ! -d "${VLLMVENV}" ]; then
    log "Creating vllmvenv (vllm 0.21+, mamba-hybrid support)…"
    uv venv --python 3.12 "${VLLMVENV}"
    VIRTUAL_ENV="${VLLMVENV}" uv pip install -q "vllm>=0.21,<0.22"
  fi
  export VLLM_PY="${VLLMVENV}/bin/python"
else
  export VLLM_PY="$(which python3)"
fi

# ----------------------------------------------------------------------------
# 4. HuggingFace cache (uses the user's existing one if set)
# ----------------------------------------------------------------------------
export HF_HUB_CACHE="${HF_HUB_CACHE:-${HOME}/.cache/huggingface/hub}"
log "HF_HUB_CACHE=${HF_HUB_CACHE}"

# ----------------------------------------------------------------------------
# 5. OpenScholar source (clone if missing)
# ----------------------------------------------------------------------------
mkdir -p external
if [ ! -d external/OpenScholar ]; then
  log "Cloning OpenScholar (citation generation only; no retrieval used)…"
  git clone --depth 1 https://github.com/AkariAsai/OpenScholar.git external/OpenScholar
fi
echo "dummy" > external/dummy_key.txt
export S2_API_KEY=dummy

# ----------------------------------------------------------------------------
# 6. .env summary
# ----------------------------------------------------------------------------
cat > .env <<EOF
# Auto-generated by 00_setup.sh
HF_HUB_CACHE=${HF_HUB_CACHE}
S2_API_KEY=dummy
PQAVENV=${PQAVENV}
OSVENV=${OSVENV}
VLLM_PY=${VLLM_PY}
EOF
log "Wrote ${ROOT}/.env"

log "Setup complete. Next: ./scripts/reproduce_minimal.sh"
